[package]
name = "player"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
rodio = "0.19.0"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros"] }
database = { path = "./database" }
metadata = { path = "./metadata" }